/* Shared-screen selection board. Bids are visually sealed, not device-private. */
(()=>{
'use strict';
const E=window.GR_SELECTION_ENGINE,D=window.GR_CHARACTER_DATA;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(text,name,attrs='',primary=false)=>`<button type="button" data-action="sel-${name}" ${attrs} class="${primary?'deal-primary':''}">${text}</button>`;
const label=c=>c.race+' '+c.cls;
function card(c,extra=''){const art=D.HERO_ART[c.faction+'|'+c.race+'|'+c.cls]||D.GREAT_REROLL_CLASS_ICONS[c.cls];return `<article class="sel-card" style="--deal-class:${D.GREAT_REROLL_CLASS_COLORS[c.cls]}"><img src="${esc(art)}" alt="" loading="lazy"><b>${esc(label(c))}</b>${extra}</article>`}
function roster(g){const s=g.selection;return `<div class="sel-rosters">${g.players.map((p,i)=>`<section class="sel-team ${s.active===i?'is-active':''} ${p.lockedCard?'is-locked':''}"><header><h3>${esc(p.name)}</h3><span>${p.lockedCard?'✓ Locked':p.points+' points'}</span></header>${s.phase==='order'?`<div class="sel-order-roll"><span>${s.scores[i].length?'D100: '+s.scores[i].join(' → '):'Not rolled'}</span>${s.pending.includes(i)?button(s.scores[i].length?'Reroll tie':'Roll D100','order',`data-player="${i}"`):''}</div>`:`<small>${p.lockedCard?'Character secured':s.active===i?'YOUR TURN':`Order #${s.order.indexOf(i)+1}`} · ${p.rerolled?'Reroll used':'Reroll available'}</small>`}<div class="sel-cards">${p.hand.map(c=>card(c)).join('')}</div></section>`).join('')}</div>`}
function pool(g){const s=g.selection,counts=new Map();for(const c of s.available){if(!counts.has(c.key))counts.set(c.key,{card:c,n:0,fresh:false});const v=counts.get(c.key);v.n++;v.fresh||=s.returned.includes(c.id)}return `<section class="sel-pool"><h3>Remaining pool <small>${s.available.length} cards</small></h3><p class="deal-muted">Available for rerolls. Gold marks newly returned cards. Cards in other hands and locked characters stay out.</p><div>${[...counts.values()].map(({card:c,n,fresh})=>`<span class="sel-pool-card ${fresh?'is-returned':''}" style="--deal-class:${D.GREAT_REROLL_CLASS_COLORS[c.cls]}">${esc(label(c))} <b>×${n}</b></span>`).join('')||'<span>No cards available yet.</span>'}</div></section>`}
function result(g){const s=g.selection,r=s.result;return `<div class="sel-results">${r.uncontested?'<p>No challenges. Character secured without spending points.</p>':r.rounds.map((rows,k)=>`<h4>${k?'Tie reroll '+k:'Contest results'}</h4><div class="sel-roll-results">${rows.map(v=>`<div><b>${esc(g.players[v.player].name)}</b><span class="sel-die">${v.roll}</span><span>+ ${v.bonus} = <strong>${v.total}</strong></span></div>`).join('')}</div>`).join('')}${s.phase==='tiebreak'?`<p>Challengers tied. Only tied challengers reroll; no extra points are spent.</p>${button('ROLL TIEBREAKER','tiebreak','',true)}`:`<h3>${esc(g.players[r.winner].name)} locks ${esc(label(r.card))}</h3>${r.winner!==s.claim.owner?`<p>${esc(g.players[s.claim.owner].name)} receives the offered card and keeps their turn.</p>`:''}${button('CONTINUE','next','',true)}`}</div>`}
function controls(g){const s=g.selection,p=g.players[s.active],c=s.claim;
 if(s.phase==='order')return `<h3>Roll for selection order</h3><p>Each player rolls D100 below. Highest goes first. Ties reroll within their tied positions.</p>`;
 if(s.phase==='done')return `<h3>Everyone has their character</h3><p>Your guild roster is locked. The unused cards remain in the pool.</p><button type="button" data-action="export">Export roster CSV</button>`;
 if(s.phase==='result'||s.phase==='tiebreak')return result(g);
 if(s.phase==='turn')return `<h3>${esc(p.name)} — choose your character</h3><p>Keep your hand and claim a hero, or use your one reroll first. Select up to three replacements; the new cards are final.</p><div class="sel-active-cards">${p.hand.map((c,j)=>card(c,`${!p.rerolled?`<label class="sel-reroll-check"><input type="checkbox" data-reroll="${j}">Replace this card</label>`:''}${button('Claim this hero','claim',`data-slot="${j}"`,true)}`)).join('')}</div>${!p.rerolled?`<div class="deal-actions">${button('Reroll selected cards','reroll','disabled')}<span id="selRerollHint" class="deal-muted">Select cards to check available replacements.</span></div>`:'<p class="deal-muted">Reroll used. Choose from your current hand.</p>'}`;
 if(s.phase==='bids'){const waiting=c.eligible.filter(i=>!Object.hasOwn(c.responses,i)),i=waiting[0];return `<h3>${esc(g.players[c.owner].name)} claims ${esc(label(g.players[c.owner].hand[c.slot]))}</h3><p>Challenge or pass · ${c.eligible.length-waiting.length} / ${c.eligible.length} responses sealed.</p><p class="deal-muted">Shared-screen mode: the host collects bids privately and enters them here. Submitted amounts stay hidden until reveal. Offers and points are locked on submission.</p><div class="sel-bid-status">${c.eligible.map(i=>`<span>${esc(g.players[i].name)}: ${Object.hasOwn(c.responses,i)?'🔒 Submitted':'Waiting'}</span>`).join('')}</div>${waiting.length?`<div class="sel-bid-form"><h4>${esc(g.players[i].name)} — your response</h4><div class="deal-controls"><label>Attack bid (0–${Math.min(s.attackCap,g.players[i].points)})<input id="selBid" type="password" inputmode="numeric" autocomplete="off" maxlength="2" aria-label="Sealed attack bid"></label><label>Card offered if you win<select id="selOffer">${E.offers(g,i).map(j=>`<option value="${j}">${esc(label(g.players[i].hand[j]))}</option>`).join('')}</select></label></div>${button('Seal attack bid','bid',`data-player="${i}"`,true)} ${button('Pass','pass',`data-player="${i}"`)}</div>`:'<p>All eligible players have responded.</p>'}${button('REVEAL ALL BIDS','reveal',waiting.length?'disabled':'',true)}`}
 if(s.phase==='defense')return `<h3>Bids revealed — ${esc(g.players[c.owner].name)} chooses defense</h3><div class="sel-bid-status">${c.attackers.map(i=>`<span><b>${esc(g.players[i].name)}: +${c.responses[i].bid}</b> · offering ${esc(label(g.players[i].hand[c.responses[i].offer]))}</span>`).join('')}</div><p>Every attack bid has been spent, even if it loses. The owner sees these bids before committing defense. All rolls happen after defense is locked.</p><div class="deal-controls"><label>Defense bonus (0–${Math.min(s.defenseCap,g.players[c.owner].points)})<input id="selDefense" type="number" min="0" max="${Math.min(s.defenseCap,g.players[c.owner].points)}" step="1" value="0"></label></div>${button('LOCK DEFENSE & ROLL','defend','',true)}<p class="deal-muted">Owner wins ties. Tied top challengers reroll without extra spending.</p>`;
 return '';
}
function render(g,content){const s=g.selection;content.innerHTML=`<div class="sel-heading"><div class="deal-kicker">THE SELECTION ROUND</div><h2>${s.phase==='done'?'Your guild roster':'Claim your character'}</h2><p class="deal-muted">${g.budget} starting points · attack cap ${s.attackCap} · defense cap ${s.defenseCap} · all committed points spent, win or lose</p></div>${s.order.length&&s.phase!=='order'?`<nav class="sel-turn-order" aria-label="Selection order">${s.order.map((i,k)=>`<span class="${s.active===i?'is-active':''}">${k+1}. ${esc(g.players[i].name)}${g.players[i].lockedCard?' ✓':''}</span>`).join('')}</nav>`:''}<section class="sel-controls">${controls(g)}</section><h3>Teams & character cards</h3>${roster(g)}${pool(g)}<details><summary>Selection rules & game log</summary><p>One shared point budget. Attack: up to 50 per claim. Defense: up to 75, limited by points remaining. Losing bids are not refunded. Only unresolved players may challenge. A challenger offers a card that preserves three different classes in the owner’s replacement hand. The winner locks the claimed hero; their unused cards return to the pool. A displaced owner keeps their turn. Each player may reroll selected cards once, on their turn before a claim. Discards return after replacements are drawn.</p><ol>${s.log.map(v=>`<li>${esc(v)}</li>`).join('')}</ol></details><button type="button" data-action="new">New game</button>`}
function slots(content){return [...content.querySelectorAll('[data-reroll]:checked')].map(e=>Number(e.dataset.reroll))}
function update(g,content){const list=slots(content),ok=E.canReroll(g,list),b=content.querySelector('[data-action="sel-reroll"]');if(b)b.disabled=!ok;const hint=content.querySelector('#selRerollHint');if(hint)hint.textContent=!list.length?'Select cards to check available replacements.':ok?`Replace ${list.length} card(s). Results are final.`:'Not enough valid replacements. Keep more cards.';}
function act(g,name,b,content){switch(name){
 case 'order':return E.rollOrder(g,Number(b.dataset.player));
 case 'reroll':return E.reroll(g,slots(content));
 case 'claim':return E.nominate(g,Number(b.dataset.slot));
 case 'bid':{const value=content.querySelector('#selBid').value;if(!/^\d+$/.test(value))throw Error('Enter a whole attack bid before sealing.');return E.respond(g,Number(b.dataset.player),Number(value),Number(content.querySelector('#selOffer').value))}
 case 'pass':return E.respond(g,Number(b.dataset.player),null);
 case 'reveal':return E.revealBids(g);
 case 'defend':{const f=content.querySelector('#selDefense');if(!f.value||!f.checkValidity())throw Error('Enter a valid whole defense bonus.');return E.defend(g,Number(f.value))}
 case 'tiebreak':return E.tiebreak(g);
 case 'next':return E.next(g);
 default:throw Error('Unknown selection action.');
}}
window.GR_SELECTION_UI={render,update,act};
})();
