/* Shared-screen selection board. Bids are visually sealed, not device-private. */
(()=>{
'use strict';
const E=window.GR_SELECTION_ENGINE,D=window.GR_CHARACTER_DATA;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(text,name,attrs='',primary=false)=>`<button type="button" data-action="sel-${name}" ${attrs} class="${primary?'deal-primary':''}">${text}</button>`;
const label=c=>c.race+' '+c.cls;
function card(c,extra=''){const art=D.HERO_ART[c.faction+'|'+c.race+'|'+c.cls]||D.GREAT_REROLL_CLASS_ICONS[c.cls];return `<article class="sel-card" style="--deal-class:${D.GREAT_REROLL_CLASS_COLORS[c.cls]}"><img src="${esc(art)}" alt="" loading="eager"><b>${esc(label(c))}</b>${extra}</article>`}
function status(g,i){const s=g.selection,p=g.players[i];if(p.lockedCard)return 'Character locked';if(s.phase==='order')return s.pending.includes(i)?'Ready to roll':'Rolled '+s.scores[i].at(-1);if(s.active===i)return s.phase==='turn'?'Choosing':s.phase==='result'?'Claim resolved':'Defending claim';if(s.phase==='bids'&&s.claim.eligible.includes(i))return Object.hasOwn(s.claim.responses,i)?'Response sealed':'Response needed';if(s.phase==='defense'&&s.claim.attackers.includes(i))return 'Challenging';return 'Waiting · #'+(s.order.indexOf(i)+1)}
function roster(g){const s=g.selection;return `<aside class="sel-roster-panel"><div class="sel-roster-title"><h3>The guild</h3><span>${g.players.filter(p=>p.lockedCard).length} / ${g.players.length} locked</span></div><div class="sel-rosters" style="--players:${g.players.length}">${(s.order.length?s.order:g.players.map((_,i)=>i)).map(i=>{const p=g.players[i];return `<section class="sel-team ${s.active===i?'is-active':''} ${p.lockedCard?'is-locked':''}"><header><h3 title="${esc(p.name)}">${s.order.length?s.order.indexOf(i)+1+'. ':''}${esc(p.name)}</h3><span>${esc(status(g,i))}</span></header><div class="sel-mini-cards">${p.hand.map(c=>`<span style="--deal-class:${D.GREAT_REROLL_CLASS_COLORS[c.cls]}" title="${esc(label(c))}"><img src="${esc(D.GREAT_REROLL_CLASS_ICONS[c.cls])}" alt=""><span>${esc(c.race)}<b>${esc(c.cls)}</b></span></span>`).join('')}</div></section>`}).join('')}</div></aside>`}
function claimCard(g){const s=g.selection,c=s.result&&(s.phase==='result'||s.phase==='tiebreak')?s.result.card:g.players[s.claim.owner].hand[s.claim.slot];return `<div class="sel-claimed-card">${card(c)}</div>`}
function progress(g){const s=g.selection;return `<nav class="sel-progress" aria-label="Game stages"><span class="is-complete">✓ The Deal</span><span class="${s.phase==='order'?'is-current':'is-complete'}" ${s.phase==='order'?'aria-current="step"':''}>${s.phase==='order'?'2':'✓'} Roll for Order</span><span class="${s.phase!=='order'?'is-current':''}" ${s.phase!=='order'?'aria-current="step"':''}>3 Claim Your Character</span></nav>`}
function pool(g){const s=g.selection,counts=new Map();for(const c of s.available){if(!counts.has(c.key))counts.set(c.key,{card:c,n:0,fresh:false});const v=counts.get(c.key);v.n++;v.fresh||=s.returned.includes(c.id)}return `<details class="sel-pool"><summary>Remaining pool · ${s.available.length} cards${s.returned.length?` · ${s.returned.length} newly returned`:""}</summary><p class="deal-muted">Available for rerolls. Gold marks newly returned cards. Cards in other hands and locked characters stay out.</p><div>${[...counts.values()].map(({card:c,n,fresh})=>`<span class="sel-pool-card ${fresh?'is-returned':''}" style="--deal-class:${D.GREAT_REROLL_CLASS_COLORS[c.cls]}">${esc(label(c))} <b>×${n}</b></span>`).join('')||'<span>No cards available yet.</span>'}</div></details>`}
function result(g){const s=g.selection,r=s.result,won=s.phase==='result';const exchanged=won&&r.winner!==s.claim.owner?g.players[s.claim.owner].hand[s.claim.slot]:null;return `<div class="sel-result-layout">${claimCard(g)}<div class="sel-results"><div class="deal-kicker">${won?'CHARACTER SECURED':'A TIE AT THE TABLE'}</div><h3>${won?esc(g.players[r.winner].name)+' locks '+esc(label(r.card)):'One more roll decides it'}</h3>${r.uncontested?'<p>Everyone passed. No points spent.</p>':r.rounds.map((rows,k)=>`<h4>${k?'Tie reroll '+k:'D100 + committed bonus'}</h4><div class="sel-roll-results">${rows.map(v=>`<div class="${won&&v.player===r.winner?'is-winner':''}"><b>${esc(g.players[v.player].name)}</b><span class="sel-die">${v.roll}</span><span class="sel-total">+ ${v.bonus} ${k?'':v.player===s.claim.owner?'defense':'attack'} = <strong>${v.total}</strong></span></div>`).join('')}</div>`).join('')}${won?`${exchanged?`<p><b>${esc(g.players[s.claim.owner].name)}</b> receives <b>${esc(label(exchanged))}</b> and keeps their turn.</p>`:''}<p class="deal-muted">Two unused cards return to the pool.${r.uncontested?'':' All committed points have been spent.'}</p>${button('Continue →','next','',true)}`:`<p>Only tied challengers reroll. No extra points spent.</p>${button('Roll tiebreaker','tiebreak','',true)}`}</div></div>`}
function controls(g){const s=g.selection,p=g.players[s.active],c=s.claim;
 if(s.phase==='order')return `<div class="deal-kicker">WHO GETS FIRST PICK?</div><h3>Roll for selection order</h3><p>Everyone rolls D100. Highest goes first; tied players roll again.</p><div class="sel-order-grid">${g.players.map((p,i)=>`<div><b>${esc(p.name)}</b><span class="sel-order-score">${s.scores[i].length?s.scores[i].join(' → '):'—'}</span>${s.pending.includes(i)?button(s.scores[i].length?'Reroll tie':'Roll D100','order',`data-player="${i}"`,true):'<small>Roll recorded</small>'}</div>`).join('')}</div>`;
 if(s.phase==='done')return `<div class="sel-finale"><div class="deal-kicker">THE GUILD IS READY</div><h3>Three cards. One final hero.</h3><p>${g.players.length} players. Your next adventure starts here.</p><button type="button" data-action="export" class="deal-primary">Save Guild Roster · CSV</button></div><div class="sel-final-gallery">${g.players.map(p=>`<section><h3>${esc(p.name)}</h3>${card(p.lockedCard)}</section>`).join('')}</div>`;
 if(s.phase==='result'||s.phase==='tiebreak')return result(g);
 if(s.phase==='turn')return `<div class="deal-kicker">YOUR TURN · ${p.points} POINTS AVAILABLE</div><h3>${esc(p.name)}, claim your character</h3><p>Pick your favorite. Everyone else gets a chance to challenge.</p><p class="deal-muted">${p.rerolled?"Your reroll is used.":"Want another shot? Keep your favorites and replace up to three cards once."}</p><div class="sel-active-cards">${p.hand.map((c,j)=>card(c,`${!p.rerolled?`<label class="sel-reroll-check"><input type="checkbox" data-reroll="${j}">Replace this card</label>`:''}${button('Claim character','claim',`data-slot="${j}"`,true)}`)).join('')}</div>${!p.rerolled?`<div class="deal-actions">${button('Reroll selected cards','reroll','disabled')}<span id="selRerollHint" class="deal-muted">Select cards to check available replacements.</span></div>`:'<p class="deal-muted">Reroll used. Choose from your current hand.</p>'}`;
 if(s.phase==='bids'){const waiting=c.eligible.filter(i=>!Object.hasOwn(c.responses,i)),i=waiting[0];return `${claimCard(g)}<div class="deal-kicker">CLAIM ON THE TABLE</div><h3>${esc(g.players[c.owner].name)} claims ${esc(label(g.players[c.owner].hand[c.slot]))}</h3><p>Challenge or pass · ${c.eligible.length-waiting.length} / ${c.eligible.length} players ready. Bids stay hidden until everyone responds.</p><p class="deal-muted">Shared-screen mode: the host collects bids privately and enters them here. Submitted amounts stay hidden until reveal. Offers and points are locked on submission.</p><div class="sel-bid-status sel-response-status">${c.eligible.map(i=>`<span>${esc(g.players[i].name)}: ${Object.hasOwn(c.responses,i)?'🔒 Submitted':'Waiting'}</span>`).join('')}</div>${waiting.length?`<div class="sel-bid-form"><h4>${esc(g.players[i].name)} — challenge or pass?</h4><p class="deal-muted">${g.players[i].points} points available. Your attack bid is spent even if you lose. Your offered card transfers only if you win.</p><div class="deal-controls"><label>Attack bid (0–${Math.min(s.attackCap,g.players[i].points)})<input id="selBid" type="password" inputmode="numeric" autocomplete="off" maxlength="2" aria-label="Sealed attack bid"></label><label>Card offered if you win<select id="selOffer">${E.offers(g,i).map(j=>`<option value="${j}">${esc(label(g.players[i].hand[j]))}</option>`).join('')}</select></label></div>${button('Seal attack bid','bid',`data-player="${i}"`,true)} ${button('Pass','pass',`data-player="${i}"`)}</div>`:'<p>All eligible players have responded.</p>'}${button('Reveal responses →','reveal',waiting.length?'disabled':'',true)}`}
 if(s.phase==='defense')return `${claimCard(g)}<div class="deal-kicker">${c.attackers.length} ${c.attackers.length===1?'CHALLENGER':'CHALLENGERS'} · BIDS REVEALED</div><h3>${esc(g.players[c.owner].name)}, defend your claim</h3><div class="sel-bid-status">${c.attackers.map(i=>`<span><b>${esc(g.players[i].name)}: +${c.responses[i].bid}</b> · offering ${esc(label(g.players[i].hand[c.responses[i].offer]))}</span>`).join('')}</div><p>Choose your defense, then everyone rolls D100 + their bonus. Highest total wins. You win ties.</p><div class="deal-controls"><label>Defense bonus (0–${Math.min(s.defenseCap,g.players[c.owner].points)})<input id="selDefense" type="number" min="0" max="${Math.min(s.defenseCap,g.players[c.owner].points)}" step="1" value="0"></label></div><p id="selDefenseHint" class="sel-spend-hint" aria-live="polite">Spend 0 points · ${g.players[c.owner].points} left. Spent points are used even if you lose.</p>${button('Commit defense & roll','defend','',true)}<p class="deal-muted">Owner wins ties. Tied top challengers reroll without extra spending.</p>`;
 return '';
}
let soundOn=false,audioContext;
function sound(kind){if(!soundOn)return;try{audioContext||=new(window.AudioContext||window.webkitAudioContext)();audioContext.resume();const now=audioContext.currentTime;const notes=kind==='next'?[392,523,659]:kind==='claim'?[220,330]:[330];notes.forEach((hz,i)=>{const o=audioContext.createOscillator(),v=audioContext.createGain();o.connect(v);v.connect(audioContext.destination);o.type='sine';o.frequency.value=hz;v.gain.setValueAtTime(0,now+i*.09);v.gain.linearRampToValueAtTime(.045,now+i*.09+.01);v.gain.exponentialRampToValueAtTime(.001,now+i*.09+.2);o.start(now+i*.09);o.stop(now+i*.09+.21)})}catch{}}
function render(g,content){const s=g.selection;content.innerHTML=`<div class="sel-shell ${s.phase==='done'?'is-finale':''}"><div class="sel-topline">${progress(g)}<button type="button" data-action="sel-sound" aria-pressed="${soundOn}">Sound: ${soundOn?'On':'Off'}</button></div><div class="sel-board">${s.phase==='done'?'':roster(g)}<main class="sel-stage"><section class="sel-controls" aria-label="Current game action">${controls(g)}</section>${pool(g)}</main></div><footer class="sel-footer"><span>${g.budget} starting points · Attack up to ${s.attackCap} · Defense up to ${s.defenseCap}</span><details><summary>How to play & game log</summary><p>Claim a character from your hand, or use your one reroll first. Other unresolved players can pass or challenge with a sealed attack bid and an offered card. After bids reveal, the owner chooses defense. D100 + bonus decides the winner; the owner wins ties. All committed points are spent, win or lose. A winning challenger swaps their offered card to the owner, who keeps their turn. The winner locks their character and returns two unused cards to the pool.</p><p>Each player has one point budget for both attack and defense. A challenge needs an offered card that preserves three different classes in the owner's hand. Players already holding the claimed combination cannot challenge for it.</p><p>Shared-screen game: collect bids privately and enter them as host. Masking is not separate-device privacy. Refreshing clears the game.</p><ol>${s.log.map(v=>`<li>${esc(v)}</li>`).join('')}</ol><button type="button" data-action="new">New game</button></details></footer></div>`}
function slots(content){return [...content.querySelectorAll('[data-reroll]:checked')].map(e=>Number(e.dataset.reroll))}
function update(g,content){const f=content.querySelector('#selDefense'),h=content.querySelector('#selDefenseHint');if(f&&h){const valid=f.value!==''&&f.checkValidity();h.textContent=valid?`Spend ${f.value} points · ${g.players[g.selection.claim.owner].points-Number(f.value)} left. Spent points are used even if you lose.`:'Enter a whole number within your remaining points and defense cap.';content.querySelector('[data-action="sel-defend"]').disabled=!valid}const list=slots(content),ok=E.canReroll(g,list),b=content.querySelector('[data-action="sel-reroll"]');if(b)b.disabled=!ok;const hint=content.querySelector('#selRerollHint');if(hint)hint.textContent=!list.length?'Select cards to check available replacements.':ok?`Replace ${list.length} card(s). Results are final.`:'Not enough valid replacements. Keep more cards.';}
function act(g,name,b,content){switch(name){
 case 'sound':soundOn=!soundOn;sound('claim');return;
 case 'order':return E.rollOrder(g,Number(b.dataset.player));
 case 'reroll':return E.reroll(g,slots(content));
 case 'claim':return E.nominate(g,Number(b.dataset.slot));
 case 'bid':{const value=content.querySelector('#selBid').value;if(!/^\d+$/.test(value))throw Error('Enter a whole attack bid before sealing.');return E.respond(g,Number(b.dataset.player),Number(value),Number(content.querySelector('#selOffer').value))}
 case 'pass':return E.respond(g,Number(b.dataset.player),null);
 case 'reveal':return E.revealBids(g);
 case 'defend':{const f=content.querySelector('#selDefense');if(!f.value||!f.checkValidity())throw Error('Enter a valid whole defense bonus.');return E.defend(g,Number(f.value))}
 case 'tiebreak':return E.tiebreak(g);
 case 'next':return E.next(g);
 default:throw Error('Unknown selection action.');
}}
window.GR_SELECTION_UI={render,update,act,sound};
})();
