const test=require('node:test'),assert=require('node:assert/strict'),Deal=require('../js/deal-engine.js'),S=require('../js/selection-engine.js');
const pool=Array.from({length:24},(_,i)=>({key:'Race'+Math.floor(i/6)+'|Class'+i%6,race:'Race'+Math.floor(i/6),cls:'Class'+i%6,faction:'Horde',flex:i%2===0}));
const seeded=seed=>()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296};
function game(n=5){const g=Deal.create(Array.from({length:n},(_,i)=>'Player '+i),pool,100,0,seeded(17),{copies:2,variety:true,balanced:true});g.phase='reveal';g.revealed=g.players.map(()=>true);S.start(g,pool);return g}
function ordered(n=5){const g=game(n);g.players.forEach((_,i)=>S.rollOrder(g,i,()=>.9-i*.1));return g}
function invariant(g){const s=g.selection,cards=[...s.available,...g.players.flatMap(p=>p.hand)];assert.equal(cards.length,s.allIds.length);assert.equal(new Set(cards.map(c=>c.id)).size,cards.length);assert.deepEqual([...cards.map(c=>c.id)].sort(),[...s.allIds].sort());g.players.forEach(p=>{assert.equal(p.hand.length,p.lockedCard?1:3);assert.equal(new Set(p.hand.map(c=>c.cls)).size,p.hand.length);assert.ok(p.points>=0&&p.points<=100)})}
function claimWith(g,count){for(let j=0;j<3;j++){S.nominate(g,j);if(g.selection.claim.eligible.length>=count)return;g.selection.phase='turn';g.selection.claim=null}throw Error('Fixture lacks enough eligible challengers')}
function bids(g,n=2,amount=50){claimWith(g,n);const c=g.selection.claim,attackers=c.eligible.slice(0,n);c.eligible.forEach(i=>S.respond(g,i,attackers.includes(i)?amount:null,attackers.includes(i)?S.offers(g,i)[0]:undefined));return attackers}
test('D100 order resolves tied positions without changing higher or lower ranks',()=>{const g=game(4);[.9,.5,.5,.1].forEach((v,i)=>S.rollOrder(g,i,()=>v));assert.deepEqual(g.selection.pending,[1,2]);S.rollOrder(g,1,()=>.2);S.rollOrder(g,2,()=>.8);assert.deepEqual(g.selection.order,[0,2,1,3]);assert.equal(g.selection.active,0);invariant(g)});
test('sealed bids stay unspent until all respond, then every attack pays including losers',()=>{const g=ordered(),attackers=bids(g);assert.ok(attackers.every(i=>g.players[i].points===100));S.revealBids(g);assert.ok(attackers.every(i=>g.players[i].points===50));const owner=g.selection.claim.owner;const rolls=[.99,0,0];S.defend(g,75,()=>rolls.shift());assert.equal(g.selection.result.winner,owner);assert.equal(g.players[owner].points,25);assert.ok(attackers.every(i=>g.players[i].points===50));assert.equal(g.selection.available.length,48-15+2);invariant(g)});
test('winning challenger exchanges offered card, releases two unused cards, skips their later turn',()=>{const g=ordered(),[winner]=bids(g,1,50),c=g.selection.claim,owner=c.owner,target=g.players[owner].hand[c.slot],offered=g.players[winner].hand[c.responses[winner].offer];S.revealBids(g);const rolls=[0,.99];S.defend(g,0,()=>rolls.shift());assert.equal(g.players[winner].lockedCard.id,target.id);assert.ok(g.players[owner].hand.some(v=>v.id===offered.id));assert.equal(g.selection.returned.length,2);invariant(g);S.next(g);assert.equal(g.selection.active,owner);assert.throws(()=>S.respond(g,winner,0,0));});
test('owner wins exact score ties; tied challengers reroll without paying again',()=>{
 const g=ordered();bids(g,1,25);S.revealBids(g);S.defend(g,25,()=>.5);assert.equal(g.selection.result.winner,g.selection.claim.owner);invariant(g);
 const h=ordered(),attackers=bids(h,2,25);S.revealBids(h);const rolls=[0,.9,.9];S.defend(h,0,()=>rolls.shift());assert.equal(h.selection.phase,'tiebreak');const before=h.players.map(p=>p.points),tie=[.2,.8];S.tiebreak(h,()=>tie.shift());assert.equal(h.selection.result.winner,attackers[1]);assert.deepEqual(h.players.map(p=>p.points),before);invariant(h);
});
test('reroll conserves cards, excludes discards until after drawing, and cannot be repeated',()=>{const g=ordered(),p=g.players[0],old=p.hand.map(c=>c.key);assert.ok(S.canReroll(g,[0,1,2]));S.reroll(g,[0,1,2],seeded(1));assert.ok(p.hand.every(c=>!old.includes(c.key)));assert.equal(g.selection.returned.length,3);assert.throws(()=>S.reroll(g,[0]));invariant(g)});
test('invalid, premature and duplicate actions leave the game unchanged',()=>{const g=ordered();S.nominate(g,0);let before=JSON.stringify(g);assert.throws(()=>S.revealBids(g));assert.equal(JSON.stringify(g),before);const i=g.selection.claim.eligible[0],offer=S.offers(g,i)[0];for(const bid of [-1,51,1.5,NaN]){assert.throws(()=>S.respond(g,i,bid,offer));assert.equal(JSON.stringify(g),before)}S.respond(g,i,50,offer);before=JSON.stringify(g);assert.throws(()=>S.respond(g,i,null));assert.equal(JSON.stringify(g),before);assert.throws(()=>S.defend(g,0));assert.equal(JSON.stringify(g),before)});
test('no challenges cost no points and release cards immediately',()=>{const g=ordered();claimWith(g,0);g.selection.claim.eligible.forEach(i=>S.respond(g,i,null));S.revealBids(g);assert.ok(g.players.every(p=>p.points===100));assert.equal(g.selection.returned.length,2);assert.equal(g.selection.phase,'result');invariant(g)});
test('many mixed games finish with one hero each and no duplicated or missing physical cards',()=>{for(let seed=1;seed<=30;seed++){const g=ordered(8),rng=seeded(seed);let count=0;while(g.selection.phase!=='done'){const s=g.selection,p=g.players[s.active];if(!p.rerolled&&S.canReroll(g,[0,1]))S.reroll(g,[0,1],rng);S.nominate(g,Math.floor(rng()*3));const c=s.claim;c.eligible.forEach(i=>{const options=S.offers(g,i);S.respond(g,i,rng()<.5?null:Math.min(50,g.players[i].points),options[0])});S.revealBids(g);if(s.phase==='defense')S.defend(g,Math.min(75,p.points),rng);while(s.phase==='tiebreak')S.tiebreak(g,rng);invariant(g);S.next(g);assert.ok(++count<=8)}assert.ok(g.players.every(p=>p.lockedCard));invariant(g)}});
test('individual rolls lock bonuses first, reject duplicate and out-of-turn rolls, then resolve',()=>{
 const g=ordered(),attackers=bids(g,2,20);S.revealBids(g);const owner=g.selection.claim.owner;S.beginDefense(g,30);assert.equal(g.players[owner].points,70);assert.equal(g.selection.phase,'rolling');
 assert.throws(()=>S.beginDefense(g,0));assert.throws(()=>S.rollContest(g,attackers[0]));const first=S.rollContest(g,owner,()=>.6);assert.equal(first.total,91);assert.equal(g.selection.phase,'rolling');assert.throws(()=>S.rollContest(g,owner));assert.throws(()=>S.respond(g,attackers[0],50,0));
 S.rollContest(g,attackers[0],()=>.99);S.rollContest(g,attackers[1],()=>.1);assert.equal(g.selection.phase,'result');assert.equal(g.selection.result.winner,attackers[0]);invariant(g);
});
test('individual tiebreaker rolls do not recharge budgets or include previous bonuses',()=>{
 const g=ordered(),attackers=bids(g,2,25);S.revealBids(g);S.beginDefense(g,0);const owner=g.selection.claim.owner;S.rollContest(g,owner,()=>0);attackers.forEach(i=>S.rollContest(g,i,()=>.9));assert.equal(g.selection.phase,'tiebreak');const budgets=g.players.map(p=>p.points);S.beginTiebreak(g);S.rollContest(g,attackers[0],()=>.2);S.rollContest(g,attackers[1],()=>.8);assert.deepEqual(g.players.map(p=>p.points),budgets);assert.ok(g.selection.result.rounds[1].every(r=>r.bonus===0));assert.equal(g.selection.result.winner,attackers[1]);invariant(g);
});
